language: ruby
sudo: false
rvm:
  - jruby-9.0.5.0
  - jruby-9.1.14.0
  - 2.2.8
  - 2.3.5
  - 2.4.2
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
before_install:
  - gem install bundler
cache: bundler
notifications:
  email: false
