language: ruby
sudo: false
matrix:
  include:
    - rvm: jruby-9.2.5.0
    - rvm: 2.4.5
    - rvm: 2.5.3
    - rvm: 2.6.3
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: 2.6.3
      install: true # This skips 'bundle install'
      script: gem build *.gemspec && gem install *.gem
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
before_install:
  - gem install bundler
cache: bundler
notifications:
  email: false
