language: ruby
sudo: false

rvm:
  - jruby-9.0.5.0
  - jruby-9.1.5.0
  - 2.2.5
  - 2.3.1
  - ruby-2.4.0-preview2
  - ruby-2.4.0-preview2-clang
  - jruby-head
  - ruby-head
  - ruby-head-clang

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-2.4.0-preview2
    - rvm: ruby-2.4.0-preview2-clang
    - rvm: ruby-head
    - rvm: ruby-head-clang
  fast_finish: true

before_install:
  - gem install bundler

cache: bundler

notifications:
  email: false
  hipchat:
    rooms:
      secure: "Scevf1Onn0h3uNLsJUPx+dyBf878/iMVWW04+GZrThA5609BQwukk1yz7dKI2fOhlwziUo878nnp2UcJ8lxT+C+3g8QG+XYZp4hI4xnRqE38oO+mwLcAPzCTemQC3+6lYY+Yv9Ux9rGZo2WHcMFHNlCPoDhIArY8qm7+BKJu1pw="
    on_success: never
    on_failure: change
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
